########################################################################
# Pointwise - Proprietary software product of Pointwise, Inc.
#             Copyright (c) 1995-2012 Pointwise, Inc.
#             All rights reserved.
#
# module.mk for src\plugins\CaeUnsRecomb2D plugin
########################################################################

########################################################################
########################################################################
#
#                   DO NOT EDIT THIS FILE
#
# To simplify SDK upgrades, the standard module.mk file should NOT be edited.
#
# If you want to modify a plugin's build process, you should rename
# modulelocal-sample.mk to modulelocal.mk and edit its settings.
#
# See the comments in modulelocal-sample.mk for more information.
#
#                   DO NOT EDIT THIS FILE
#
########################################################################
########################################################################

CaeUnsRecomb2D_LOC := $(PLUGINS_LOC)/CaeUnsRecomb2D
CaeUnsRecomb2D_LIB := CaeUnsRecomb2D$(DBG_SUFFIX)
CaeUnsRecomb2D_CXX_LOC := $(CaeUnsRecomb2D_LOC)
CaeUnsRecomb2D_OBJ_LOC := $(PLUGINS_OBJ_LOC)/CaeUnsRecomb2D

CaeUnsRecomb2D_FULLNAME := lib$(CaeUnsRecomb2D_LIB).$(SHLIB_SUFFIX)
CaeUnsRecomb2D_FULLLIB := $(PLUGINS_DIST_DIR)/$(CaeUnsRecomb2D_FULLNAME)

CaeUnsRecomb2D_DEPS = \
	$(NULL)

MODCXXFILES := \
	CaeUnsPluginRecomb2D.cxx \
	Edge.cxx \
	runtimeWrite.cxx \
	$(NULL)

# IMPORTANT:
# Must recompile the shared/XXX/.cxx files for each plugin. These .cxx files
# include the plugin specific settings defined in the ./CaeUnsRecomb2D/*.h
# files.
CaeUnsRecomb2D_SRC := \
	$(PLUGINS_RT_PWPSRC) \
	$(PLUGINS_RT_PWGMSRC) \
	$(PLUGINS_RT_CAEPSRC) \
	$(patsubst %,$(CaeUnsRecomb2D_CXX_LOC)/%,$(MODCXXFILES))

CaeUnsRecomb2D_SRC_CXX := $(filter %.cxx,$(MODCXXFILES))

# place the .o files generated from shared sources in the plugin's
# OBJ folder.
CaeUnsRecomb2D_OBJ := \
	$(patsubst %.cxx,$(CaeUnsRecomb2D_OBJ_LOC)/%.o,$(PLUGINS_RT_PWPFILES)) \
	$(patsubst %.cxx,$(CaeUnsRecomb2D_OBJ_LOC)/%.o,$(PLUGINS_RT_PWGMFILES)) \
	$(patsubst %.cxx,$(CaeUnsRecomb2D_OBJ_LOC)/%.o,$(PLUGINS_RT_CAEPFILES)) \
    $(patsubst %.cxx,$(CaeUnsRecomb2D_OBJ_LOC)/%.o,$(CaeUnsRecomb2D_SRC_CXX)) \
	$(NULL)

# To allow over-rides, search FIRST for headers in the local module's folder.
# For example, a site.h file in the local module's folder will preempt the
# file .../src/plugins/site.h
CaeUnsRecomb2D_INCL = \
	-I$(CaeUnsRecomb2D_LOC) \
	$(PLUGINS_RT_INCL) \
	$(NULL)

CaeUnsRecomb2D_LIBS = \
	$(NULL)

CaeUnsRecomb2D_MAINT_TARGETS := \
    CaeUnsRecomb2D_info \
    CaeUnsRecomb2D_install \
    CaeUnsRecomb2D_installnow \
    CaeUnsRecomb2D_uninstall


########################################################################
# Get (OPTIONAL) locally defined make targets. If a plugin developer wants
# to extend a plugin's make scheme, they should create a modulelocal.mk file
# in the plugin's base folder. To provide for future SDK upgrades, the standard
# module.mk file should NOT be directly edited.
#
ifneq ($(wildcard $(CaeUnsRecomb2D_LOC)/modulelocal.mk),)
    CaeUnsRecomb2D_DEPS += $(CaeUnsRecomb2D_LOC)/modulelocal.mk
    include $(CaeUnsRecomb2D_LOC)/modulelocal.mk
endif


# merge in plugin private settings

CaeUnsRecomb2D_OBJ += \
    $(patsubst %.cxx,$(CaeUnsRecomb2D_OBJ_LOC)/%.o,$(filter %.cxx,$(CaeUnsRecomb2D_CXXFILES_PRIVATE))) \
	$(NULL)

CaeUnsRecomb2D_SRC += \
	$(patsubst %,$(CaeUnsRecomb2D_CXX_LOC)/%,$(CaeUnsRecomb2D_CXXFILES_PRIVATE)) \
	$(NULL)

CaeUnsRecomb2D_INCL += $(CaeUnsRecomb2D_INCL_PRIVATE)
CaeUnsRecomb2D_LIBS += $(CaeUnsRecomb2D_LIBS_PRIVATE)
CaeUnsRecomb2D_CXXFLAGS += $(CaeUnsRecomb2D_CXXFLAGS_PRIVATE)
CaeUnsRecomb2D_LDFLAGS += $(CaeUnsRecomb2D_LDFLAGS_PRIVATE)
CaeUnsRecomb2D_MAINT_TARGETS += $(CaeUnsRecomb2D_MAINT_TARGETS_PRIVATE)
CaeUnsRecomb2D_DEPS += $(CaeUnsRecomb2D_DEPS_PRIVATE)

PLUGIN_MAINT_TARGETS += $(CaeUnsRecomb2D_MAINT_TARGETS)
PLUGIN_OBJ += $(CaeUnsRecomb2D_OBJ)

# add to plugin maint targets to the global .PHONY target
.PHONY: \
	$(CaeUnsRecomb2D_MAINT_TARGETS) \
	$(NULL)


########################################################################
# Set the final build macros
CaeUnsRecomb2D_CXXFLAGS += $(CXXFLAGS) $(PLUGINS_STDDEFS) $(CaeUnsRecomb2D_INCL) \
    -DPWGM_HIDE_STRUCTURED_API


ifeq ($(machine),macosx)
CaeUnsRecomb2D_LDFLAGS += -install_name "$(REL_BIN_TO_PW_LIB_DIR)/$(CaeUnsRecomb2D_FULLNAME)"
else
CaeUnsRecomb2D_LDFLAGS +=
endif


########################################################################
# list of plugin's build targets
#
CaeUnsRecomb2D: $(CaeUnsRecomb2D_FULLLIB)

$(CaeUnsRecomb2D_FULLLIB): $(CaeUnsRecomb2D_OBJ) $(CaeUnsRecomb2D_DEPS)
	@echo "***"
	@echo "*** $@"
	@echo "***"
	@mkdir -p $(PLUGINS_DIST_DIR)
	$(SHLIB_LD) $(ARCH_FLAGS) $(CaeUnsRecomb2D_LDFLAGS) -o $(CaeUnsRecomb2D_FULLLIB) $(CaeUnsRecomb2D_OBJ) $(CaeUnsRecomb2D_LIBS) $(SYS_LIBS)

CaeUnsRecomb2D_info:
	@echo ""
	@echo "--------------------------------------------------------------"
ifeq ($(machine),macosx)
	otool -L -arch all $(CaeUnsRecomb2D_FULLLIB)
	@echo ""
endif
	file $(CaeUnsRecomb2D_FULLLIB)
	@echo "--------------------------------------------------------------"
	@echo ""


########################################################################
# list of plugin's intermediate targets
#
$(CaeUnsRecomb2D_OBJ_LOC):
	mkdir -p $(CaeUnsRecomb2D_OBJ_LOC)

#.......................................................................
# build .d files for the plugin and each of the shared runtime sources
# the .d files will be placed in the plugins OBJ folder CaeUnsRecomb2D_OBJ_LOC
$(CaeUnsRecomb2D_OBJ_LOC)/%.d: $(CaeUnsRecomb2D_CXX_LOC)/%.cxx
	@echo "Updating dependencies $(CaeUnsRecomb2D_OBJ_LOC)/$*.d"
	@mkdir -p $(CaeUnsRecomb2D_OBJ_LOC)
	@./depend.sh $(CaeUnsRecomb2D_OBJ_LOC) $(CaeUnsRecomb2D_CXXFLAGS) $< > $@

$(CaeUnsRecomb2D_OBJ_LOC)/%.d: $(PLUGINS_RT_PWPLOC)/%.cxx
	@echo "Updating dependencies $(CaeUnsRecomb2D_OBJ_LOC)/$*.d"
	@mkdir -p $(CaeUnsRecomb2D_OBJ_LOC)
	@./depend.sh $(CaeUnsRecomb2D_OBJ_LOC) $(CaeUnsRecomb2D_CXXFLAGS) $< > $@

$(CaeUnsRecomb2D_OBJ_LOC)/%.d: $(PLUGINS_RT_PWGMLOC)/%.cxx
	@echo "Updating dependencies $(CaeUnsRecomb2D_OBJ_LOC)/$*.d"
	@mkdir -p $(CaeUnsRecomb2D_OBJ_LOC)
	@./depend.sh $(CaeUnsRecomb2D_OBJ_LOC) $(CaeUnsRecomb2D_CXXFLAGS) $< > $@

$(CaeUnsRecomb2D_OBJ_LOC)/%.d: $(PLUGINS_RT_CAEPLOC)/%.cxx
	@echo "Updating dependencies $(CaeUnsRecomb2D_OBJ_LOC)/$*.d"
	@mkdir -p $(CaeUnsRecomb2D_OBJ_LOC)
	@./depend.sh $(CaeUnsRecomb2D_OBJ_LOC) $(CaeUnsRecomb2D_CXXFLAGS) $< > $@

#.......................................................................
# build .o files for the plugin and each of the shared runtime sources.
# the .o files will be placed in the plugins OBJ folder CaeUnsRecomb2D_OBJ_LOC
$(CaeUnsRecomb2D_OBJ_LOC)/%.o: $(CaeUnsRecomb2D_CXX_LOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(CaeUnsRecomb2D_OBJ_LOC)
	$(CXX) $(CaeUnsRecomb2D_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<

$(CaeUnsRecomb2D_OBJ_LOC)/%.o: $(PLUGINS_RT_PWPLOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(CaeUnsRecomb2D_OBJ_LOC)
	$(CXX) $(CaeUnsRecomb2D_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<

$(CaeUnsRecomb2D_OBJ_LOC)/%.o: $(PLUGINS_RT_PWGMLOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(CaeUnsRecomb2D_OBJ_LOC)
	$(CXX) $(CaeUnsRecomb2D_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<

$(CaeUnsRecomb2D_OBJ_LOC)/%.o: $(PLUGINS_RT_CAEPLOC)/%.cxx
	@echo "***"
	@echo "*** $*"
	@echo "***"
	@mkdir -p $(CaeUnsRecomb2D_OBJ_LOC)
	$(CXX) $(CaeUnsRecomb2D_CXXFLAGS) $(ARCH_FLAGS) -o $@ -c $<


########################################################################
# list of plugin's clean targets
#
CaeUnsRecomb2D_cleandep:
	-$(RMR) $(CaeUnsRecomb2D_OBJ_LOC)/*.d

CaeUnsRecomb2D_clean:
	-$(RMR) $(CaeUnsRecomb2D_OBJ_LOC)/*.{d,o}

CaeUnsRecomb2D_distclean: CaeUnsRecomb2D_clean
	-$(RMF) $(CaeUnsRecomb2D_FULLLIB) > /dev/null 2>&1

########################################################################
# list of plugin's clean targets
#
CaeUnsRecomb2D_install: install_validate CaeUnsRecomb2D_installnow
	@echo "CaeUnsRecomb2D Installed to '$(PLUGIN_INSTALL_FULLPATH)'"

CaeUnsRecomb2D_installnow:
	-@$(CP) $(CaeUnsRecomb2D_FULLLIB) "$(PLUGIN_INSTALL_FULLPATH)/libCaeUnsRecomb2D.$(SHLIB_SUFFIX)"

CaeUnsRecomb2D_uninstall:
	@echo "CaeUnsRecomb2D Uninstalled from '$(PLUGIN_INSTALL_FULLPATH)'"
	-@$(RMF) "$(PLUGIN_INSTALL_FULLPATH)/libCaeUnsRecomb2D.$(SHLIB_SUFFIX)"
